"""new changes

Revision ID: 66ecf0533c77
Revises: 313050c7f4e8
Create Date: 2025-11-13 15:33:29.109293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '66ecf0533c77'
down_revision: Union[str, Sequence[str], None] = '313050c7f4e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('previous_caller')
        batch_op.drop_column('previous_categories')

    with op.batch_alter_table('product_customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('order_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('extra', sa.JSON(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_event_customers_id'))
        batch_op.create_index(batch_op.f('ix_product_customers_id'), ['id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_name', sa.Integer(), nullable=True))
        batch_op.alter_column('start_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_events_id'))
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_id'))
        batch_op.create_index(batch_op.f('ix_events_id'), ['id'], unique=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('type_name')

    with op.batch_alter_table('product_customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_customers_id'))
        batch_op.create_index(batch_op.f('ix_event_customers_id'), ['id'], unique=False)
        batch_op.drop_column('extra')
        batch_op.drop_column('order_date')
        batch_op.drop_column('type_status')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_categories', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('previous_caller', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###
