"""status -> type_status

Revision ID: 764db1abccba
Revises: 80ea6e1f3b01
Create Date: 2025-11-15 13:06:39.386909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764db1abccba'
down_revision: Union[str, Sequence[str], None] = '80ea6e1f3b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Update type_status and limit status to 3 where needed
    op.execute("""
        UPDATE product_customers
        SET type_status = status,
            status = 3
        WHERE status > 3
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
