"""Type_id nullable false default value

Revision ID: 80ea6e1f3b01
Revises: 8120346c5e08
Create Date: 2025-11-14 16:03:01.798455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '80ea6e1f3b01'
down_revision: Union[str, Sequence[str], None] = '8120346c5e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Fill existing rows with default value
    op.execute(
        "UPDATE products SET type_id = 'p1' WHERE type_id IS NULL"
    )

    # ### commands auto generated by Alembic - please adjust! ###
#    op.drop_table('_alembic_tmp_products')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('type_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('type_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

#    op.create_table('_alembic_tmp_products',
#    sa.Column('id', sa.INTEGER(), nullable=False),
#    sa.Column('type_id', sa.VARCHAR(), nullable=False),
#    sa.Column('name', sa.VARCHAR(), nullable=False),
#    sa.Column('price', sa.INTEGER(), nullable=True),
#    sa.Column('description', sa.VARCHAR(), nullable=True),
#    sa.Column('start_date', sa.DATETIME(), nullable=True),
#    sa.Column('end_date', sa.DATETIME(), nullable=True),
#    sa.Column('type_a', sa.BOOLEAN(), nullable=True),
#    sa.Column('type_b', sa.BOOLEAN(), nullable=True),
#    sa.Column('type_c', sa.BOOLEAN(), nullable=True),
#    sa.Column('type_d', sa.BOOLEAN(), nullable=True),
#    sa.Column('type_e', sa.BOOLEAN(), nullable=True),
#    sa.Column('type_f', sa.BOOLEAN(), nullable=True),
#    sa.Column('type_g', sa.BOOLEAN(), nullable=True),
#    sa.Column('type_h', sa.BOOLEAN(), nullable=True),
#    sa.Column('extra_external', sa.BOOLEAN(), nullable=True),
#    sa.Column('extra_non_political', sa.BOOLEAN(), nullable=True),
#    sa.Column('extra_visilble_all', sa.BOOLEAN(), nullable=True),
#    sa.Column('extra', sqlite.JSON(), nullable=True),
#    sa.PrimaryKeyConstraint('id')
#    )
    # ### end Alembic commands ###
