"""Type_id

Revision ID: 8120346c5e08
Revises: 66ecf0533c77
Create Date: 2025-11-14 15:20:47.819321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8120346c5e08'
down_revision: Union[str, Sequence[str], None] = '66ecf0533c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', sa.String(), nullable=True))
        batch_op.drop_column('type_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_name', sa.INTEGER(), nullable=True))
        batch_op.drop_column('type_id')

    # ### end Alembic commands ###
